run:
  timeout: 5m

output:
  formats:
    - format: line-number
      path: stderr

linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - exhaustive
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nolintlint
    - nonamedreturns
    - predeclared
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - sloglint

linters-settings:
  goimports:
    local-prefixes: "github.com/prometheus-community/yet-another-cloudwatch-exporter"
