name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: prometheus/promci@52c7012f5f0070d7281b8db4a119e21341d43c91 # v0.4.5
      - uses: ./.github/promci/actions/setup_environment
      - run: make
      - run: mkdir .build
      - uses: ./.github/promci/actions/save_artifacts
        with:
          directory: .build
      - run: git diff --exit-code

  verify-example-configs:
    name: Verify
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make build
      - name: Verify example configs
        run: find ./examples -name "*.yml" -print0 | xargs -0 -I % ./yace verify-config -config.file %

  publish_master:
    name: Publish master branch artifacts
    runs-on: ubuntu-latest
    needs: [build, verify-example-configs]
    if: |
      (github.repository == 'prometheus-community/yet-another-cloudwatch-exporter')
      &&
      (github.event_name == 'push' && github.event.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: prometheus/promci@52c7012f5f0070d7281b8db4a119e21341d43c91 # v0.4.5
      - uses: ./.github/promci/actions/publish_main
        with:
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}

  publish_release:
    name: Publish release artifacts
    runs-on: ubuntu-latest
    needs: [build, verify-example-configs]
    if: |
      (github.repository == 'prometheus-community/yet-another-cloudwatch-exporter')
      &&
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v.'))
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: prometheus/promci@52c7012f5f0070d7281b8db4a119e21341d43c91 # v0.4.5
      - uses: ./.github/promci/actions/publish_release
        with:
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}
          github_token: ${{ secrets.PROMBOT_GITHUB_TOKEN }}
